name: beacons
description: Flutter beacons plugin for iOS and Android.
version: 0.3.3
author: Loup Inc. <hello@intheloup.io>
homepage: https://github.com/loup-v/beacons

environment:
  sdk: '>=1.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  streams_channel:
    git:
      url: git://github.com/loup-v/streams_channel.git
      ref: 5e5241a1a8fc3d500b50c4145c31b5fa46a9dfd9

flutter:
  plugin:
    androidPackage: io.intheloup.beacons
    pluginClass: BeaconsPlugin
